# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded aed::cli 1.0 [list source [file join $dir cli.tcl]]
package ifneeded aed::defib 1.0 [list source [file join $dir defib.tcl]]
package ifneeded aed::manager 1.0 [list source [file join $dir manager.tcl]]
package ifneeded aed::module 1.0 [list source [file join $dir module.tcl]]
package ifneeded aed 1.0 [list source [file join $dir aed.tcl]]
