# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -load aed::modules" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded aed::modules::mysql 5.5 [list source [file join $dir mysql55.tcl]]
package ifneeded aed::modules::mysql 5.1 [list source [file join $dir mysql51.tcl]]
package ifneeded aed::modules::redis 2.6 [list source [file join $dir redis26.tcl]]
package ifneeded aed::modules::redis 2.4 [list source [file join $dir redis24.tcl]]
package ifneeded aed::modules::erlang 15.03 [list source [file join $dir erlangR15B03.tcl]]
