# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded aed::managers::darwin::homebrew 1.0 [list source [file join $dir homebrew.tcl]]
package ifneeded aed::managers::darwin::macports 1.0 [list source [file join $dir macports.tcl]]
package ifneeded aed::managers 1.0 [list source [file join $dir managers.tcl]]
